version: '3'

services:

    marley-postgres:
        image: "postgres:13.0-alpine"
        container_name: marley-postgres
        #Volume mounted for database for the storage
        volumes:
          - marley-data:/var/lib/postgresql/data
        ports:
          - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine
    
        #Environment variable for DB name, user and password
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    face-recognition:
      build: ./python
      container_name: face-recognition

      environment:
        - MONGO_CLIENT=${MONGO_CLIENT}
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - PYTHONUNBUFFERED=1
      ports:
        - 5000:5000

    
    person-recognition:
        build: ./server
        container_name: person-recognition

        environment:
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_URL=${DB_URL}
          - FACE_REC_URL=${FACE_REC_URL}
        ports:
            - 8080:8080
        depends_on:
            - marley-postgres
            - face-recognition
        
#Volumes for DB data
volumes:
    marley-data: