FROM python:3.6-slim-stretch

RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN mkdir -p dlib && \
    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS

RUN cd ..
RUN pip install numpy
RUN pip install Flask
RUN pip install flask-restx
RUN python -m pip install pymongo
RUN pip install pymongo[srv]
RUN pip install -U python-dotenv
RUN pip install face_recognition
RUN pip install waitress

COPY . /usr/face_recognition/

EXPOSE 5000

CMD [ "python3", "/usr/face_recognition/face_recognition_api.py" ]